# Generated by Django 5.0.2 on 2024-02-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chooser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='site_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
